# Uncomment the following lines to enable the Corne RGB Underglow
# CONFIG_ZMK_RGB_UNDERGLOW=y
# CONFIG_WS2812_STRIP=y
# Erhöht die Sendeleistung (hilft bei Verbindungsabbrüchen zwischen den Hälften)
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
# Bluetooth-Verbindung stabilisieren
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n

# Falls du Verbindungsprobleme mit Windows hast:
CONFIG_ZMK_BLE_PASSKEY_ENTRY=n

# Ermöglicht das Umschalten zwischen mehreren Geräten (Profilen)
CONFIG_BT_MAX_CONN=5
CONFIG_BT_MAX_PAIRED=5
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000